# Generated by Django 4.0.4 on 2022-05-28 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=50)),
                ('crc', models.CharField(max_length=50, verbose_name='Conselho Regional de Classe')),
                ('redes_sociais', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DosesTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarme', models.DateTimeField()),
                ('compartimento_caixa', models.CharField(max_length=10, verbose_name='Compartimento')),
                ('tempo_alerta_especifico', models.CharField(max_length=20, verbose_name='Tempo de alerta')),
                ('status_ingestao', models.BooleanField(verbose_name='Status da Ingestão')),
                ('status_sincronizacao', models.BooleanField(verbose_name='Status da Sincronização')),
                ('status_tratamento', models.BooleanField(verbose_name='Status do Tratamento')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comercial', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=50, verbose_name='Laboratório')),
                ('principio_ativo', models.CharField(max_length=255, verbose_name='Princípio Ativo')),
                ('dose_diaria_maxima', models.IntegerField(verbose_name='Dose Diária Máxima')),
                ('forma_farmaceutica', models.CharField(max_length=50, verbose_name='Forma Farmacêutica')),
                ('concentracao', models.CharField(max_length=10, verbose_name='Concentração')),
                ('via_administracao', models.CharField(max_length=50, verbose_name='Via de administração')),
                ('grupo_etario', models.CharField(max_length=50, verbose_name='Grupo Etário')),
                ('tarja', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('documento', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=20)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('anamnese', models.TextField()),
                ('redes_sociais', models.CharField(max_length=255)),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('consultorio', models.CharField(max_length=255, verbose_name='Consultório')),
                ('email', models.EmailField(max_length=254)),
                ('redes_sociais', models.CharField(max_length=255)),
                ('crc', models.CharField(max_length=50, verbose_name='Conselho Regional de Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prescricao', models.DateField(verbose_name='Data da Prescrição')),
                ('frequencia_diaria', models.IntegerField(verbose_name='Frequência Diária')),
                ('horarios_diarios', models.CharField(max_length=255, verbose_name='Horários Diários')),
                ('dose', models.DecimalField(decimal_places=3, max_digits=7)),
                ('unidade_medida', models.CharField(max_length=100, verbose_name='Unidade de Medida')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de início')),
                ('tipo_tratamento', models.BooleanField(verbose_name='Tipo de Tratamento')),
                ('periodo_tratamento', models.IntegerField(verbose_name='Período de Tratamento')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Término do Tratamento')),
                ('observacao', models.TextField(verbose_name='Observação')),
                ('lote', models.CharField(max_length=50)),
                ('validade', models.DateField()),
                ('embalagem_fracionavel', models.BooleanField()),
                ('quantidade_total_embalagem', models.IntegerField(verbose_name='Quantidade Total por Embalagem')),
                ('amostra_gratis', models.BooleanField(verbose_name='Amostra Grátis')),
                ('status_tratamento', models.BooleanField()),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.paciente')),
                ('prescrito_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.profissionalsaude')),
            ],
        ),
    ]
