# Generated by Django 4.0.4 on 2022-05-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_cuidador_redes_sociais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='crc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Conselho Regional de Classe'),
        ),
    ]
