# Generated by Django 4.0.4 on 2022-09-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_cuidador_usuario_dosestratamento_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidador',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='dosestratamento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='tratamento',
            name='usuario',
        ),
    ]
