# Generated by Django 4.1.2 on 2022-11-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_dosestratamento_alarme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosestratamento',
            name='alarme',
            field=models.DateTimeField(),
        ),
    ]
